set(_AMENT_PACKAGE_NAME "wavemaker_controller")
set(wavemaker_controller_VERSION "0.0.0")
set(wavemaker_controller_MAINTAINER "hydrolab-linux <vebjorn.steinsholt@ntnu.no>")
set(wavemaker_controller_BUILD_DEPENDS "lifecycle_msgs" "rclcpp" "rclcpp_lifecycle" "wavemaker_interfaces" "bondcpp" "rclcpp_action" "mgate5101_driver" "std_msgs")
set(wavemaker_controller_BUILDTOOL_DEPENDS "ament_cmake")
set(wavemaker_controller_BUILD_EXPORT_DEPENDS "lifecycle_msgs" "rclcpp" "rclcpp_lifecycle" "wavemaker_interfaces" "bondcpp" "rclcpp_action" "mgate5101_driver" "std_msgs")
set(wavemaker_controller_BUILDTOOL_EXPORT_DEPENDS )
set(wavemaker_controller_EXEC_DEPENDS "lifecycle_msgs" "rclcpp" "rclcpp_lifecycle" "wavemaker_interfaces" "bondcpp" "rclcpp_action" "mgate5101_driver" "std_msgs")
set(wavemaker_controller_TEST_DEPENDS "ament_lint_auto" "ament_lint_common" "ament_cmake_gtest")
set(wavemaker_controller_GROUP_DEPENDS )
set(wavemaker_controller_MEMBER_OF_GROUPS )
set(wavemaker_controller_DEPRECATED "")
set(wavemaker_controller_EXPORT_TAGS)
list(APPEND wavemaker_controller_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
