set(_AMENT_PACKAGE_NAME "wavemaker_interfaces")
set(wavemaker_interfaces_VERSION "0.0.0")
set(wavemaker_interfaces_MAINTAINER "hydrolab-linux <vebjorn.steinsholt@ntnu.no>")
set(wavemaker_interfaces_BUILD_DEPENDS )
set(wavemaker_interfaces_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(wavemaker_interfaces_BUILD_EXPORT_DEPENDS )
set(wavemaker_interfaces_BUILDTOOL_EXPORT_DEPENDS )
set(wavemaker_interfaces_EXEC_DEPENDS )
set(wavemaker_interfaces_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(wavemaker_interfaces_GROUP_DEPENDS )
set(wavemaker_interfaces_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(wavemaker_interfaces_DEPRECATED "")
set(wavemaker_interfaces_EXPORT_TAGS)
list(APPEND wavemaker_interfaces_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
