set(_AMENT_PACKAGE_NAME "wavemaker_bringup")
set(wavemaker_bringup_VERSION "0.0.0")
set(wavemaker_bringup_MAINTAINER "hydrolab-linux <vebjorn.steinsholt@ntnu.no>")
set(wavemaker_bringup_BUILD_DEPENDS )
set(wavemaker_bringup_BUILDTOOL_DEPENDS "ament_cmake")
set(wavemaker_bringup_BUILD_EXPORT_DEPENDS )
set(wavemaker_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(wavemaker_bringup_EXEC_DEPENDS "wavemaker_controller" "nav2_lifecycle_manager")
set(wavemaker_bringup_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(wavemaker_bringup_GROUP_DEPENDS )
set(wavemaker_bringup_MEMBER_OF_GROUPS )
set(wavemaker_bringup_DEPRECATED "")
set(wavemaker_bringup_EXPORT_TAGS)
list(APPEND wavemaker_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
