set(_AMENT_PACKAGE_NAME "mgate5101_driver")
set(mgate5101_driver_VERSION "0.1.0")
set(mgate5101_driver_MAINTAINER "Vebjørn Steinsholt <vebjorn.steinsholt@ntnu.no>")
set(mgate5101_driver_BUILD_DEPENDS )
set(mgate5101_driver_BUILDTOOL_DEPENDS "ament_cmake")
set(mgate5101_driver_BUILD_EXPORT_DEPENDS )
set(mgate5101_driver_BUILDTOOL_EXPORT_DEPENDS )
set(mgate5101_driver_EXEC_DEPENDS )
set(mgate5101_driver_TEST_DEPENDS )
set(mgate5101_driver_GROUP_DEPENDS )
set(mgate5101_driver_MEMBER_OF_GROUPS )
set(mgate5101_driver_DEPRECATED "")
set(mgate5101_driver_EXPORT_TAGS)
list(APPEND mgate5101_driver_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
